experiment:
    project: "titok_l_32_stage1"
    name: "titok_l_32_stage1_run2"
    output_dir: "titok_l_32_stage1_run2"
    max_train_examples: 1_281_167
    save_every: 5_000
    eval_every: 1_000
    generate_every: 2_000    #5_000
    log_every: 50
    log_grad_norm_every: 1_000
    resume: True     # True default ; but a loss NaN error, so re-training from scratch
    init_weight: "/home/ma-user/modelarts/work/jjw/SFT/lqf/pretrained_ckpt/TiTok/tokenizer_titok_l32.bin"


model:
    vq_model:
        # codebook_size: 4096
        finetune_multi_depth: True
        token_size: 12
        # use_l2_norm: True
        commitment_cost: 0.25
        entropy_loss_weight: 0.02
        entropy_loss_temperature: 0.01
        entropy_gamma: 1.0
        quantize_mode: "lfq"
        # vit arch
        vit_enc_model_size: "large"
        vit_dec_model_size: "large"
        vit_enc_patch_size: 16
        vit_dec_patch_size: 16
        num_latent_tokens: 32
        finetune_decoder: False
        pretrained_tokenizer_weight: "/home/ma-user/modelarts/work/jjw/SFT/lqf/pretrained_ckpt/TiTok/maskgit-vqgan-imagenet-f16-256.bin"

losses:
    quantizer_weight: 1.0

dataset:
    params:
        train_shards_path_or_url: "/home/ma-user/modelarts/work/jjw/SFT/lqf/webimagenet/train/imagenet-train-{0000..0252}.tar"
        eval_shards_path_or_url: "/home/ma-user/modelarts/work/jjw/SFT/lqf/webimagenet/val/imagenet-val-{0000..0009}.tar"
        num_workers_per_gpu: 12
    preprocessing:
        resize_shorter_edge: 256
        crop_size: 256
        random_crop: True
        random_flip: True

optimizer:
    name: adamw 
    params:
        learning_rate: 1e-4
        beta1: 0.9
        beta2: 0.99
        weight_decay: 1e-4
        epsilon: 1e-8

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 10_000
        end_lr: 1e-5

training:
    gradient_accumulation_steps: 1
    per_gpu_batch_size: 64
    mixed_precision: "fp16"
    enable_tf32: True
    enable_wandb: True
    use_ema: True
    seed: 42
    max_train_steps: 1_000_000
    num_generated_images: 2
    max_grad_norm: 1.0